import base64

from aidialog.dialog import Dialog, Message, snote, sraw, code_output
from aidialog.ipynb import write_ipynb

from mdhtml.readme import main

PNG_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='


def mk_project(tmp_path):
    (tmp_path/'pyproject.toml').write_text('[project]\nname = "demo"\n\n[tool.nbdev]\nnbs_path = "notebooks"\n')
    nbs = tmp_path/'notebooks'
    nbs.mkdir()
    img_out = [dict(output_type='display_data', data={'image/png': PNG_B64}, metadata={})]
    att = Message('A ![plot](attachment:img1.png) attachment.', msg_type=snote)
    att.mk_attachment(base64.b64decode(PNG_B64), 'image/png', 'img1.png')
    d = Dialog(name='index', messages=[
        Message('---\nskip_exec: true\n---', msg_type=sraw),
        Message('#| hide\nfrom demo import *'),
        Message('import secret_setup', meta={'nbdev': {'hide': ''}}),
        Message('# demo\n\n> A demo package', msg_type=snote),
        Message('#| export\nShown *prose*.', msg_type=snote),
        Message('1+1', output=code_output('2')),
        Message('plot()', output=img_out),
        att])
    write_ipynb(d, nbs/'index.ipynb')
    return nbs


def test_readme(tmp_path, monkeypatch):
    nbs = mk_project(tmp_path)
    (tmp_path/'README_files').mkdir()
    (tmp_path/'README_files'/'stale.png').write_bytes(b'x')
    monkeypatch.chdir(nbs)                                      # config found by walking up
    main.__wrapped__()
    out = (tmp_path/'README.md').read_text()
    assert out.startswith('<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->\n\n# demo')
    assert 'from demo import' not in out and 'secret_setup' not in out  # hide cells drop, comment or meta form
    assert 'skip_exec' not in out                               # leading frontmatter is consumed
    assert '# demo' in out and 'Shown *prose*.' in out
    assert '#|' not in out                                      # directive lines strip
    assert '```python\n1+1\n```' in out and '2' in out
    assert 'data:image' not in out and 'attachment:' not in out
    names = sorted(p.name for p in (tmp_path/'README_files').iterdir())
    assert len(names) == 1                                      # both images share one extracted file
    assert f'README_files/{names[0]}' in out
    assert 'stale.png' not in names                             # the CLI owns and clears its subdir
    main.__wrapped__(head='')
    assert (tmp_path/'README.md').read_text().startswith('# demo')      # '' suppresses the warning
    main.__wrapped__(head='<!-- custom -->')
    assert (tmp_path/'README.md').read_text().startswith('<!-- custom -->\n\n# demo')
